services:
  qt-app:
    build: .  # Ключевое изменение - собираем из Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
    network_mode: host
    # Для Windows:
    extra_hosts:
      - "host.docker.internal:host-gateway"